import "./globals.css";
import Header from "./components/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body className="h-screen bg-#FFFFFF">
        <Header /> {children}
      </body>
    </html>
  );
}
